package main;

// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: TPCompilador/AnalizadorLexico/Lexico.flex

import java_cup.runtime.Symbol;
import jflex.core.sym;



// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;
  
  public String s = "";

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\22\0\1\1"+
    "\1\0\1\5\3\0\1\6\1\0\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\12\17\1\20\1\21"+
    "\1\22\1\23\1\24\2\0\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\2\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\36\1\44\1\45\1\46\2\36"+
    "\1\47\3\36\1\50\1\0\1\51\1\0\1\36\1\0"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\1\62\2\36\1\63\1\64\1\65\1\66\1\67\1\36"+
    "\1\70\1\71\1\72\2\36\1\73\3\36\1\74\1\75"+
    "\1\76\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\12\1\1\1\13\1\14"+
    "\1\15\1\16\7\17\1\20\1\21\6\17\1\22\1\1"+
    "\1\23\1\0\1\24\1\25\1\12\1\26\1\0\1\27"+
    "\1\0\1\30\1\31\1\15\1\32\3\17\1\33\11\17"+
    "\1\34\2\0\14\17\1\35\2\17\1\0\7\17\1\0"+
    "\7\17\1\0\3\17\1\36\1\37\2\17\1\0\3\17"+
    "\1\0\2\17\1\0\2\17\1\40\1\0\2\17\1\0"+
    "\2\17\1\0\1\17\1\41\1\0\2\17\1\0\1\17"+
    "\1\0\2\17\1\0\1\17\1\0\2\17\1\0\1\17"+
    "\1\0\2\17\1\0\1\17\1\0\2\17\1\0\1\17"+
    "\1\0\2\17\1\0\1\17\1\0\1\17\1\42\1\0"+
    "\1\17\1\0\1\17\1\0\1\17\2\43\1\0\1\17"+
    "\1\0\1\17\1\0\1\17\2\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\77\0\176\0\275\0\77\0\77\0\77"+
    "\0\77\0\77\0\374\0\u013b\0\77\0\u017a\0\u01b9\0\77"+
    "\0\u01f8\0\u0237\0\u0276\0\u02b5\0\u02f4\0\u0333\0\u0372\0\u03b1"+
    "\0\u03f0\0\u042f\0\77\0\77\0\u046e\0\u04ad\0\u04ec\0\u052b"+
    "\0\u056a\0\u05a9\0\77\0\u05e8\0\77\0\176\0\77\0\77"+
    "\0\u0627\0\u013b\0\u0666\0\77\0\u06a5\0\77\0\77\0\77"+
    "\0\77\0\u06e4\0\u0723\0\u0762\0\u02b5\0\u07a1\0\u07e0\0\u081f"+
    "\0\u085e\0\u089d\0\u08dc\0\u091b\0\u095a\0\u0999\0\77\0\u09d8"+
    "\0\u0a17\0\u0a56\0\u0a95\0\u0ad4\0\u0b13\0\u0b52\0\u0b91\0\u0bd0"+
    "\0\u0c0f\0\u0c4e\0\u0c8d\0\u0ccc\0\u0d0b\0\77\0\u0d4a\0\u0d89"+
    "\0\u0dc8\0\u0e07\0\u0e46\0\u0e85\0\u0ec4\0\u0f03\0\u0f42\0\u0f81"+
    "\0\u0fc0\0\u0fff\0\u103e\0\u107d\0\u10bc\0\u10fb\0\u113a\0\u1179"+
    "\0\u11b8\0\u11f7\0\u1236\0\u1275\0\u02b5\0\u02b5\0\u12b4\0\u12f3"+
    "\0\u1332\0\u1371\0\u13b0\0\u13ef\0\u142e\0\u146d\0\u14ac\0\u14eb"+
    "\0\u152a\0\u1569\0\u02b5\0\u15a8\0\u15e7\0\u1626\0\u1665\0\u16a4"+
    "\0\u16e3\0\u1722\0\u1761\0\u02b5\0\u17a0\0\u17df\0\u181e\0\u185d"+
    "\0\u189c\0\u18db\0\u191a\0\u1959\0\u1998\0\u19d7\0\u1a16\0\u1a55"+
    "\0\u1a94\0\u1ad3\0\u1b12\0\u1b51\0\u1b90\0\u1bcf\0\u1c0e\0\u1c4d"+
    "\0\u1c8c\0\u1ccb\0\u1d0a\0\u1d49\0\u1d88\0\u1dc7\0\u1e06\0\u1e45"+
    "\0\u1e84\0\u1ec3\0\u1f02\0\u1f41\0\u02b5\0\u1f80\0\u1fbf\0\u1ffe"+
    "\0\u203d\0\u207c\0\u20bb\0\77\0\u02b5\0\u20fa\0\u2139\0\u2178"+
    "\0\u21b7\0\u21f6\0\u2235\0\77\0\u02b5";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\24\1\26"+
    "\1\27\3\24\1\30\5\24\1\31\3\24\1\32\1\33"+
    "\1\34\1\24\1\35\1\24\1\36\1\37\3\24\1\40"+
    "\4\24\1\41\3\24\1\42\1\43\1\44\1\45\77\0"+
    "\2\46\1\0\2\46\1\47\71\46\6\0\1\50\107\0"+
    "\1\51\76\0\1\52\73\0\1\53\1\52\1\0\1\16"+
    "\5\0\23\24\2\0\22\24\26\0\1\54\71\0\1\55"+
    "\4\0\1\56\1\57\75\0\1\60\76\0\1\61\72\0"+
    "\1\24\5\0\23\24\2\0\22\24\22\0\1\24\5\0"+
    "\4\24\1\62\16\24\2\0\22\24\22\0\1\24\5\0"+
    "\4\24\1\63\16\24\2\0\22\24\22\0\1\24\5\0"+
    "\14\24\1\64\6\24\2\0\22\24\22\0\1\24\5\0"+
    "\5\24\1\65\6\24\1\66\6\24\2\0\5\24\1\65"+
    "\14\24\22\0\1\24\5\0\17\24\1\67\3\24\2\0"+
    "\22\24\22\0\1\24\5\0\7\24\1\70\13\24\2\0"+
    "\22\24\22\0\1\24\5\0\23\24\2\0\4\24\1\71"+
    "\15\24\22\0\1\24\5\0\23\24\2\0\4\24\1\72"+
    "\15\24\22\0\1\24\5\0\23\24\2\0\13\24\1\73"+
    "\6\24\22\0\1\24\5\0\23\24\2\0\5\24\1\65"+
    "\5\24\1\74\6\24\22\0\1\24\5\0\23\24\2\0"+
    "\16\24\1\75\3\24\22\0\1\24\5\0\23\24\2\0"+
    "\7\24\1\76\12\24\100\0\1\77\15\0\1\53\1\52"+
    "\1\0\1\51\76\0\1\100\57\0\16\55\1\101\60\55"+
    "\17\0\1\24\5\0\6\24\1\102\14\24\2\0\22\24"+
    "\22\0\1\24\5\0\2\24\1\103\20\24\2\0\22\24"+
    "\22\0\1\24\5\0\3\24\1\104\17\24\2\0\22\24"+
    "\22\0\1\24\5\0\12\24\1\105\10\24\2\0\22\24"+
    "\22\0\1\24\5\0\10\24\1\106\12\24\2\0\22\24"+
    "\22\0\1\24\5\0\10\24\1\107\12\24\2\0\22\24"+
    "\22\0\1\24\5\0\23\24\2\0\6\24\1\110\13\24"+
    "\22\0\1\24\5\0\23\24\2\0\2\24\1\111\17\24"+
    "\22\0\1\24\5\0\23\24\2\0\3\24\1\112\16\24"+
    "\22\0\1\24\5\0\23\24\2\0\11\24\1\113\10\24"+
    "\22\0\1\24\5\0\23\24\2\0\10\24\1\114\11\24"+
    "\22\0\1\24\5\0\23\24\2\0\10\24\1\115\11\24"+
    "\17\0\1\53\1\52\1\0\1\100\57\0\16\55\1\101"+
    "\5\55\1\116\52\55\17\0\1\24\5\0\10\24\1\117"+
    "\12\24\2\0\22\24\22\0\1\24\5\0\12\24\1\120"+
    "\10\24\2\0\22\24\3\0\2\121\3\0\12\121\1\122"+
    "\5\121\3\122\1\123\17\122\2\121\22\122\3\121\17\0"+
    "\1\24\5\0\10\24\1\124\12\24\2\0\22\24\22\0"+
    "\1\24\5\0\14\24\1\125\6\24\2\0\22\24\22\0"+
    "\1\24\5\0\12\24\1\126\10\24\2\0\22\24\22\0"+
    "\1\24\5\0\23\24\2\0\10\24\1\127\11\24\22\0"+
    "\1\24\5\0\23\24\2\0\11\24\1\130\10\24\3\0"+
    "\2\131\3\0\12\131\1\132\5\131\23\132\2\131\3\132"+
    "\1\133\16\132\3\131\17\0\1\24\5\0\23\24\2\0"+
    "\10\24\1\134\11\24\22\0\1\24\5\0\23\24\2\0"+
    "\13\24\1\135\6\24\22\0\1\24\5\0\23\24\2\0"+
    "\11\24\1\136\10\24\22\0\1\24\5\0\14\24\1\137"+
    "\6\24\2\0\22\24\22\0\1\24\5\0\1\140\22\24"+
    "\2\0\22\24\46\0\1\141\52\0\1\24\5\0\16\24"+
    "\1\142\4\24\2\0\22\24\22\0\1\24\5\0\4\24"+
    "\1\143\11\24\1\142\4\24\2\0\22\24\22\0\1\24"+
    "\5\0\20\24\1\144\2\24\2\0\22\24\22\0\1\24"+
    "\5\0\21\24\1\145\1\24\2\0\22\24\22\0\1\24"+
    "\5\0\4\24\1\146\16\24\2\0\22\24\22\0\1\24"+
    "\5\0\23\24\2\0\13\24\1\147\6\24\22\0\1\24"+
    "\5\0\23\24\2\0\1\150\21\24\72\0\1\151\26\0"+
    "\1\24\5\0\23\24\2\0\15\24\1\152\4\24\22\0"+
    "\1\24\5\0\23\24\2\0\4\24\1\153\10\24\1\152"+
    "\4\24\22\0\1\24\5\0\23\24\2\0\17\24\1\154"+
    "\2\24\22\0\1\24\5\0\23\24\2\0\20\24\1\145"+
    "\1\24\22\0\1\24\5\0\23\24\2\0\4\24\1\146"+
    "\15\24\3\0\2\155\3\0\12\155\1\156\5\155\23\156"+
    "\2\155\22\156\3\155\17\0\1\24\5\0\17\24\1\157"+
    "\3\24\2\0\22\24\47\0\1\160\51\0\1\24\5\0"+
    "\17\24\1\161\3\24\2\0\22\24\22\0\1\24\5\0"+
    "\2\24\1\162\20\24\2\0\22\24\22\0\1\24\5\0"+
    "\21\24\1\163\1\24\2\0\22\24\3\0\2\164\3\0"+
    "\12\164\1\165\5\164\23\165\2\164\22\165\3\164\17\0"+
    "\1\24\5\0\23\24\2\0\16\24\1\166\3\24\73\0"+
    "\1\167\25\0\1\24\5\0\23\24\2\0\16\24\1\170"+
    "\3\24\22\0\1\24\5\0\23\24\2\0\2\24\1\171"+
    "\17\24\22\0\1\24\5\0\23\24\2\0\20\24\1\163"+
    "\1\24\46\0\1\172\52\0\1\24\5\0\16\24\1\173"+
    "\4\24\2\0\22\24\22\0\1\24\5\0\4\24\1\174"+
    "\16\24\2\0\22\24\45\0\1\175\53\0\1\24\5\0"+
    "\15\24\1\176\5\24\2\0\22\24\22\0\1\24\5\0"+
    "\12\24\1\177\10\24\2\0\22\24\72\0\1\200\26\0"+
    "\1\24\5\0\23\24\2\0\15\24\1\201\4\24\22\0"+
    "\1\24\5\0\23\24\2\0\4\24\1\174\15\24\71\0"+
    "\1\202\27\0\1\24\5\0\23\24\2\0\14\24\1\203"+
    "\5\24\22\0\1\24\5\0\23\24\2\0\11\24\1\204"+
    "\10\24\47\0\1\205\51\0\1\24\5\0\17\24\1\206"+
    "\3\24\2\0\22\24\36\0\1\207\62\0\1\24\5\0"+
    "\6\24\1\210\14\24\2\0\22\24\22\0\1\24\5\0"+
    "\1\211\22\24\2\0\22\24\73\0\1\212\25\0\1\24"+
    "\5\0\23\24\2\0\16\24\1\213\3\24\63\0\1\214"+
    "\35\0\1\24\5\0\23\24\2\0\6\24\1\215\13\24"+
    "\22\0\1\24\5\0\23\24\2\0\1\216\21\24\45\0"+
    "\1\217\53\0\1\24\5\0\15\24\1\220\5\24\2\0"+
    "\22\24\47\0\1\221\51\0\1\24\5\0\17\24\1\222"+
    "\3\24\2\0\22\24\22\0\1\24\5\0\17\24\1\223"+
    "\3\24\2\0\22\24\71\0\1\224\27\0\1\24\5\0"+
    "\23\24\2\0\14\24\1\225\5\24\73\0\1\226\25\0"+
    "\1\24\5\0\23\24\2\0\16\24\1\227\3\24\22\0"+
    "\1\24\5\0\23\24\2\0\16\24\1\230\3\24\36\0"+
    "\1\231\62\0\1\24\5\0\6\24\1\232\14\24\2\0"+
    "\22\24\30\0\1\233\70\0\1\24\5\0\1\234\22\24"+
    "\2\0\22\24\22\0\1\24\5\0\4\24\1\235\16\24"+
    "\2\0\22\24\63\0\1\236\35\0\1\24\5\0\23\24"+
    "\2\0\6\24\1\237\13\24\55\0\1\240\43\0\1\24"+
    "\5\0\23\24\2\0\1\241\21\24\22\0\1\24\5\0"+
    "\23\24\2\0\4\24\1\235\15\24\47\0\1\242\51\0"+
    "\1\24\5\0\17\24\1\243\3\24\2\0\22\24\43\0"+
    "\1\244\55\0\1\24\5\0\13\24\1\245\7\24\2\0"+
    "\22\24\73\0\1\246\25\0\1\24\5\0\23\24\2\0"+
    "\16\24\1\247\3\24\67\0\1\244\31\0\1\24\5\0"+
    "\23\24\2\0\12\24\1\245\7\24\30\0\1\250\70\0"+
    "\1\24\5\0\1\251\22\24\2\0\22\24\55\0\1\252"+
    "\43\0\1\24\5\0\23\24\2\0\1\253\21\24\43\0"+
    "\1\254\55\0\1\24\5\0\13\24\1\255\7\24\2\0"+
    "\22\24\67\0\1\254\31\0\1\24\5\0\23\24\2\0"+
    "\12\24\1\255\7\24\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8820];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\5\11\2\1\1\11\2\1\1\11"+
    "\12\1\2\11\6\1\1\11\1\1\1\11\1\0\2\11"+
    "\2\1\1\0\1\11\1\0\4\11\15\1\1\11\2\0"+
    "\14\1\1\11\2\1\1\0\7\1\1\0\7\1\1\0"+
    "\7\1\1\0\3\1\1\0\2\1\1\0\3\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\2\1\1\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\2\1\1\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\11\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
	final int MAX_STRING = 30;
	final int MAX_INT = Short.MAX_VALUE;
	final float MAX_FLOAT = Float.MAX_VALUE;

	private boolean verify_real(String x) {
		float f = Float.parseFloat(x);
		if (f < -MAX_FLOAT || f > MAX_FLOAT) {
			throw new NumberFormatException();
		}
		return true;
	}

	private boolean verify_int(String x) {
		int i = Integer.parseInt(x);
		if (i < -MAX_INT || i > MAX_INT) {
			throw new NumberFormatException();
		}
		return true;
	}

	private boolean verify_string(String x) {
		if (x.length() > MAX_STRING) {
			throw new NumberFormatException();
		}
		return true;
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la linea " + yyline);
            }
            // fall through
          case 37: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 38: break;
          case 3:
            { System.out.println("Token ParA encontrado, Lexema "+ yytext());
            s=s+"Token ParA encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 39: break;
          case 4:
            { System.out.println("Token ParC encontrado, Lexema "+ yytext());
            s=s+"Token ParC encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 40: break;
          case 5:
            { System.out.println("Token Multiplicacion encontrado, Lexema "+ yytext());
            s=s+"Token Multiplicacion encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 41: break;
          case 6:
            { System.out.println("Token Suma encontrado, Lexema "+ yytext());
            s=s+"Token Suma encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 42: break;
          case 7:
            { System.out.println("Token Coma encontrado, Lexema "+ yytext());
            s=s+"Token Coma encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 43: break;
          case 8:
            { System.out.println("Token Resta encontrado, Lexema "+ yytext());
            s=s+"Token Resta encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 44: break;
          case 9:
            { System.out.println("Token Division encontrado, Lexema "+ yytext());
            s=s+"Token Division encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 45: break;
          case 10:
            { verify_int(yytext());
				System.out.println("Token Numero encontrado, Lexema "+ yytext());
				s=s+"Token Numero encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 46: break;
          case 11:
            { System.out.println("Token PuntoC encontrado, Lexema "+ yytext());
            s=s+"Token PuntoC encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 47: break;
          case 12:
            { System.out.println("Token Menor encontrado, Lexema "+ yytext());
            s=s+"Token Menor encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 48: break;
          case 13:
            { System.out.println("Token Igual encontrado, Lexema "+ yytext());
            s=s+"Token Igual encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 49: break;
          case 14:
            { System.out.println("Token Mayor encontrado, Lexema "+ yytext());
            s=s+"Token Mayor encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 50: break;
          case 15:
            { System.out.println("Token VarId encontrado, Lexema "+ yytext());
            s=s+"Token VarId encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 51: break;
          case 16:
            { System.out.println("Token CorcheteA encontrado, Lexema "+ yytext());
            s=s+"Token CorcheteA encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 52: break;
          case 17:
            { System.out.println("Token CorcheteC encontrado, Lexema "+ yytext());
            s=s+"Token CorcheteC encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 53: break;
          case 18:
            { System.out.println("Token LlaveA encontrado, Lexema "+ yytext());
            s=s+"Token LlaveA encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 54: break;
          case 19:
            { System.out.println("Token LlaveC encontrado, Lexema "+ yytext());
            s=s+"Token LlaveC encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 55: break;
          case 20:
            { verify_string(yytext());
							System.out.println("Token String encontrado, Lexema "+ yytext());
							s=s+"Token String encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 56: break;
          case 21:
            { System.out.println("Token And encontrado, Lexema "+ yytext());
            s=s+"Token And encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 57: break;
          case 22:
            { verify_real(yytext());
				System.out.println("Token Real encontrado, Lexema "+ yytext());
				s=s+"Token Real encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 58: break;
          case 23:
            { System.out.println("Token Asignacion encontrado, Lexema "+ yytext());
            s=s+"Token Asignacion encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 59: break;
          case 24:
            { System.out.println("Token MenorI encontrado, Lexema "+ yytext());
            s=s+"Token MenorI encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 60: break;
          case 25:
            { System.out.println("Token Distinto encontrado, Lexema "+ yytext());
            s=s+"Token Distinto encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 61: break;
          case 26:
            { System.out.println("Token MayorI encontrado, Lexema "+ yytext());
            s=s+"Token MayorI encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 62: break;
          case 27:
            { System.out.println("Token If encontrado, Lexema "+ yytext());
            s=s+"Token If encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 63: break;
          case 28:
            { System.out.println("Token Or encontrado, Lexema "+ yytext());
            s=s+"Token Or encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 64: break;
          case 29:
            { /**/
            }
            // fall through
          case 65: break;
          case 30:
            { System.out.println("Token Print encontrado, Lexema "+ yytext());
            s=s+"Token Print encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 66: break;
          case 31:
            { System.out.println("Token While encontrado, Lexema "+ yytext());
            s=s+"Token While encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 67: break;
          case 32:
            { System.out.println("Token InList encontrado, Lexema "+ yytext());
            s=s+"Token InList encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 68: break;
          case 33:
            { System.out.println("Token DeclareB encontrado, Lexema "+ yytext());
            s=s+"Token DeclareB encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 69: break;
          case 34:
            { System.out.println("Token DeclareE encontrado, Lexema "+ yytext());
            s=s+"Token DeclareE encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 70: break;
          case 35:
            { System.out.println("Token ProgramE encontrado, Lexema "+ yytext());
            s=s+"Token ProgramE encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 71: break;
          case 36:
            { System.out.println("Token ProgramB encontrado, Lexema "+ yytext());
            s=s+"Token ProgramB encontrado, Lexema "+ yytext()+"\n";
            }
            // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
